name: Python CI

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - master
      - release/*
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Output my name, group, and GitHub username
        run: |
          echo "Full Name: Иван Иванов"
          echo "Group Number: 123456"
          echo "GitHub Username: ${{ github.actor }}"

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Check code style with flake8
        run: |
          pip install flake8
          flake8 .

      - name: Format code with black (optional)
        run: |
          pip install black
          black --check .
